DROP TABLE IF exists "CATEGORY";
CREATE TABLE "CATEGORY"(
    CATEGORY_ID INTEGER AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR (255) NOT NULL,
    PRIMARY KEY (CATEGORY_ID)
);

DROP TABLE IF exists "GOODS";
CREATE TABLE "GOODS"(
  GOODS_ID INTEGER AUTO_INCREMENT,
  GOODS_NAME VARCHAR(255) NOT NULL,
  GOODS_PRICE INTEGER NOT NULL,
  GOODS_CATEGORY_ID INTEGER NOT NULL,
  GOODS_IMAGE_SRC VARCHAR (255) NOT NULL,
  GOODS_NAVIGATOR_URL VARCHAR (255) NOT NULL,
  PRIMARY KEY (GOODS_ID)
);

DROP TABLE IF exists "USER";
CREATE TABLE "USER"(
    OPEN_ID varchar (255) NOT NULL,
    NICK_NAME varchar(255) NOT NULL,
    GENDER INTEGER NOT NULL,
    LANGUAGE varchar (255) NOT NULL,
    CITY varchar (255) NOT NULL,
    PROVINCE varchar (255) NOT NULL,
    COUNTRY varchar (255) NOT NULL,
    AVATAR_URL varchar (255) NOT NULL,
    TOKEN varchar (255) NOT NULL,
    PRIMARY KEY (OPEN_ID)
);
DROP TABLE IF EXISTS "ORDER1";
CREATE TABLE "ORDER1"(
    ORDER_ID INTEGER AUTO_INCREMENT,
    ORDER_PRICE INTEGER NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    USER_ID varchar (255) NOT NULL,
    ADDRESS varchar (255) NOT NULL,
    ORDER_STATE INTEGER (255) NOT NULL,
    PRIMARY KEY (ORDER_ID)
)